# Generated by Django 4.2.16 on 2024-10-11 17:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('company_about', models.TextField(default='')),
                ('company_phone', models.CharField(max_length=30)),
                ('company_address', models.TextField(default='')),
                ('city', models.TextField(default='')),
                ('state', models.TextField(default='')),
                ('country', models.TextField(default='')),
                ('zipcode', models.TextField(default='')),
                ('company_website', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyInstagram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(default='')),
                ('active', models.BooleanField(default=False)),
                ('linked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField(default='')),
                ('active', models.BooleanField(default=True)),
                ('permissions', models.JSONField(default={})),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reputation_app.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyPosts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platforms', models.JSONField(default={'comment': None, 'platform': None, 'uploaded': None})),
                ('content', models.TextField(default='')),
                ('is_uploaded', models.BooleanField(default=True)),
                ('has_media', models.BooleanField(default=True)),
                ('date_uploaded', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='')),
                ('commentor', models.CharField(max_length=100)),
                ('date_commented', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media', models.ImageField(upload_to='scheduled_media/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reputation_app.companyposts')),
            ],
        ),
        migrations.CreateModel(
            name='MessageReplies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversation_id', models.IntegerField(default=0)),
                ('reply_id', models.IntegerField(default=0)),
                ('message', models.TextField(default='')),
                ('date_sent', models.DateTimeField(default=django.utils.timezone.now)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiving_user', to='reputation_app.companymember')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sending_user', to='reputation_app.companymember')),
            ],
        ),
        migrations.CreateModel(
            name='MemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MemberMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sent', models.DateTimeField(default=django.utils.timezone.now)),
                ('conversation_id', models.IntegerField(default=0)),
                ('recipients', models.ManyToManyField(related_name='recipient', to='reputation_app.companymember')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reputation_app.companymember')),
            ],
        ),
        migrations.AddField(
            model_name='companymember',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reputation_app.memberprofile'),
        ),
        migrations.CreateModel(
            name='CompanyContacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram', models.TextField(default='', null=True)),
                ('facebook', models.TextField(default='', null=True)),
                ('whatsapp', models.TextField(default='', null=True)),
                ('twitter', models.TextField(default='', null=True)),
                ('email', models.TextField(default='', null=True)),
                ('linkedin', models.TextField(default='', null=True)),
                ('youtube', models.TextField(default='', null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reputation_app.company')),
            ],
        ),
    ]
