# Generated by Django 4.2.16 on 2024-10-14 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reputation_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_profile',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='companymember',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companyreviews',
            name='platform',
            field=models.TextField(default=''),
        ),
    ]
