# Generated by Django 4.2.16 on 2024-10-14 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reputation_app', '0002_company_company_profile_companymember_is_admin_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company_profile',
            new_name='company_category',
        ),
        migrations.AddField(
            model_name='company',
            name='company_address2',
            field=models.TextField(default='', null=True),
        ),
    ]
