# Generated by Django 4.2.16 on 2024-10-14 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reputation_app', '0003_rename_company_profile_company_company_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_id',
            field=models.CharField(default='id', max_length=255),
        ),
    ]
