# Generated by Django 4.2.16 on 2024-10-15 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reputation_app', '0004_company_company_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymember',
            name='permissions',
            field=models.JSONField(default={}, null=True),
        ),
    ]
