# Generated by Django 4.2.16 on 2024-10-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reputation_app', '0005_alter_companymember_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companymember',
            name='permissions',
            field=models.JSONField(blank=True, default={}),
        ),
    ]
