# Generated by Django 4.2.16 on 2024-10-15 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reputation_app', '0008_alter_company_company_about_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfilePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_pic', models.ImageField(upload_to='company_profile/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reputation_app.company')),
            ],
        ),
    ]
