# Generated by Django 4.2.16 on 2024-10-15 10:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reputation_app', '0010_company_company_active_subscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_free_trial_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 20, 10, 19, 2, 508822, tzinfo=datetime.timezone.utc)),
        ),
    ]
