# Generated by Django 4.2.16 on 2024-10-15 10:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reputation_app', '0011_company_company_free_trial_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_link',
            field=models.CharField(default='link', max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_free_trial_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 20, 10, 25, 48, 776084, tzinfo=datetime.timezone.utc)),
        ),
    ]
