# Generated by Django 4.2.16 on 2024-10-15 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reputation_app', '0012_company_company_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_free_trial_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 20, 15, 26, 28, 380626, tzinfo=datetime.timezone.utc)),
        ),
    ]
