# Generated by Django 4.2.16 on 2024-10-15 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reputation_app', '0013_alter_company_company_free_trial_expiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_free_trial_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 20, 18, 11, 41, 282628, tzinfo=datetime.timezone.utc)),
        ),
    ]
