# Generated by Django 4.2.16 on 2024-10-16 13:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reputation_app', '0016_alter_company_company_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyposts',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reputation_app.company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_free_trial_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 21, 13, 36, 50, 440409, tzinfo=datetime.timezone.utc)),
        ),
    ]
