# Generated by Django 4.2.16 on 2024-10-17 17:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reputation_app', '0017_companyposts_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyposts',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companyposts',
            name='engagement_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companyposts',
            name='is_scheduled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companyposts',
            name='tags',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_free_trial_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 22, 17, 2, 51, 252746, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companyposts',
            name='platforms',
            field=models.JSONField(default=[]),
        ),
        migrations.CreateModel(
            name='CompanyPostsComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reputation_app.companyposts')),
            ],
        ),
    ]
