# Generated by Django 4.2.16 on 2024-10-23 20:51

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reputation_app', '0018_companyposts_comment_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_free_trial_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 28, 20, 51, 30, 457872, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='CompanyTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=50)),
                ('team_about', models.TextField(default='')),
                ('date_created', models.DateField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reputation_app.company')),
                ('members', models.ManyToManyField(related_name='team_members', to='reputation_app.memberprofile')),
            ],
        ),
    ]
