# Generated by Django 4.2.16 on 2024-10-24 14:38

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reputation_app', '0019_alter_company_company_free_trial_expiry_companyteam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_free_trial_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 29, 14, 38, 48, 724954, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='CompanyTeamChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default='')),
                ('date_sent', models.DateTimeField(default=django.utils.timezone.now)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reputation_app.memberprofile')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reputation_app.companyteam')),
            ],
        ),
    ]
