# Generated by Django 4.2.16 on 2024-10-24 17:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reputation_app', '0020_alter_company_company_free_trial_expiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_free_trial_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 29, 17, 55, 28, 291834, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='MemberPP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='member_profile_picture/')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reputation_app.memberprofile')),
            ],
        ),
    ]
