# Generated by Django 4.2.16 on 2024-10-25 21:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reputation_app', '0021_alter_company_company_free_trial_expiry_memberpp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_free_trial_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 30, 21, 38, 55, 286634, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='CompanyTeamInviteLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=255)),
                ('permissions', models.JSONField(default=[])),
                ('active', models.BooleanField(default=True)),
                ('num_members', models.IntegerField(default=0)),
                ('max_members', models.IntegerField(default=0)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reputation_app.companyteam')),
            ],
        ),
    ]
