# Generated by Django 4.2.16 on 2024-10-25 21:46

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reputation_app', '0022_alter_company_company_free_trial_expiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyteaminvitelinks',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_free_trial_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 30, 21, 46, 50, 31569, tzinfo=datetime.timezone.utc)),
        ),
    ]
