# Generated by Django 4.2.16 on 2024-11-04 17:30

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reputation_app', '0027_rename_token_companyinstagram_account_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_free_trial_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 9, 17, 30, 55, 583249, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companyinstagram',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 1, 3, 17, 30, 55, 588248, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='CompanyTiktok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('linked', models.BooleanField(default=False)),
                ('access_token', models.TextField(default='')),
                ('refresh_token', models.TextField(default='')),
                ('token_expiry', models.DateField(default=datetime.datetime(2025, 1, 3, 17, 30, 55, 589248, tzinfo=datetime.timezone.utc))),
                ('account_name', models.TextField(default='')),
                ('account_username', models.TextField(default='')),
                ('profile_url', models.TextField(default='')),
                ('account_id', models.TextField(default='')),
                ('account_type', models.TextField(default='')),
                ('followers_count', models.JSONField(default={})),
                ('likes_count', models.JSONField(default={})),
                ('profile_views', models.JSONField(default={})),
                ('reach', models.JSONField(default={})),
                ('last_update_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reputation_app.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyFacebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('linked', models.BooleanField(default=False)),
                ('page_id', models.TextField(default='')),
                ('short_lived_token', models.TextField(default='')),
                ('long_lived_token', models.TextField(default='')),
                ('token_expiry', models.DateField(default=datetime.datetime(2025, 1, 3, 17, 30, 55, 588248, tzinfo=datetime.timezone.utc))),
                ('account_name', models.TextField(default='')),
                ('profile_url', models.TextField(default='')),
                ('account_id', models.TextField(default='')),
                ('followers_trend', models.JSONField(default={})),
                ('impressions', models.JSONField(default={})),
                ('profile_views', models.JSONField(default={})),
                ('reach', models.JSONField(default={})),
                ('page_engaged_users', models.JSONField(default={})),
                ('page_fans', models.JSONField(default={})),
                ('page_views_total', models.JSONField(default={})),
                ('page_negative_feedback', models.JSONField(default={})),
                ('last_update_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reputation_app.company')),
            ],
        ),
    ]
