# Generated by Django 4.2.16 on 2024-11-04 21:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reputation_app', '0028_alter_company_company_free_trial_expiry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_free_trial_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 9, 21, 39, 19, 190605, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companyfacebook',
            name='followers_trend',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='companyfacebook',
            name='impressions',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='companyfacebook',
            name='page_engaged_users',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='companyfacebook',
            name='page_fans',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='companyfacebook',
            name='page_negative_feedback',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='companyfacebook',
            name='page_views_total',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='companyfacebook',
            name='profile_views',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='companyfacebook',
            name='reach',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='companyfacebook',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 1, 3, 21, 39, 19, 200639, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companyinstagram',
            name='followers_trend',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='companyinstagram',
            name='impressions',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='companyinstagram',
            name='profile_views',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='companyinstagram',
            name='reach',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='companyinstagram',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 1, 3, 21, 39, 19, 199637, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companytiktok',
            name='followers_count',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='companytiktok',
            name='likes_count',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='companytiktok',
            name='profile_views',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='companytiktok',
            name='reach',
            field=models.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='companytiktok',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 1, 3, 21, 39, 19, 201835, tzinfo=datetime.timezone.utc)),
        ),
    ]
