# Generated by Django 4.2.16 on 2024-11-05 19:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reputation_app', '0031_alter_company_company_free_trial_expiry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinstagram',
            name='account_type',
        ),
        migrations.RemoveField(
            model_name='companyinstagram',
            name='profile_views',
        ),
        migrations.AlterField(
            model_name='company',
            name='company_free_trial_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 10, 19, 53, 56, 479828, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companyfacebook',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 1, 4, 19, 53, 56, 484828, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companyinstagram',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 1, 4, 19, 53, 56, 484828, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companytiktok',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 1, 4, 19, 53, 56, 485827, tzinfo=datetime.timezone.utc)),
        ),
    ]
