# Generated by Django 4.2.16 on 2024-11-06 16:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reputation_app', '0032_remove_companyinstagram_account_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_free_trial_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 11, 16, 57, 41, 323682, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companyfacebook',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 1, 5, 16, 57, 41, 328675, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companyinstagram',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 1, 5, 16, 57, 41, 327639, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companytiktok',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 1, 5, 16, 57, 41, 328675, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='CompanyReddit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('linked', models.BooleanField(default=False)),
                ('access_token', models.TextField(default='')),
                ('refresh_token', models.TextField(default='')),
                ('account_name', models.TextField(default='')),
                ('account_username', models.TextField(default='')),
                ('profile_url', models.TextField(default='')),
                ('account_id', models.TextField(default='')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reputation_app.company')),
            ],
        ),
    ]
