# Generated by Django 4.2.16 on 2024-11-06 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reputation_app', '0033_alter_company_company_free_trial_expiry_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyreddit',
            old_name='account_id',
            new_name='comment_karma',
        ),
        migrations.RenameField(
            model_name='companyreddit',
            old_name='account_name',
            new_name='link_karma',
        ),
        migrations.AlterField(
            model_name='company',
            name='company_free_trial_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 11, 17, 2, 32, 63532, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companyfacebook',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 1, 5, 17, 2, 32, 68544, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companyinstagram',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 1, 5, 17, 2, 32, 68544, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companytiktok',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 1, 5, 17, 2, 32, 69545, tzinfo=datetime.timezone.utc)),
        ),
    ]
