# Generated by Django 4.2.16 on 2024-11-13 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reputation_app', '0035_companyfacebookposts_companyinstagramposts_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyfacebookposts',
            name='is_scheduled',
        ),
        migrations.RemoveField(
            model_name='companyinstagramposts',
            name='is_scheduled',
        ),
        migrations.RemoveField(
            model_name='companyredditposts',
            name='is_scheduled',
        ),
        migrations.RemoveField(
            model_name='companytiktokposts',
            name='is_scheduled',
        ),
        migrations.AlterField(
            model_name='company',
            name='company_free_trial_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 18, 19, 3, 55, 249659, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companyfacebook',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 1, 12, 19, 3, 55, 255771, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companyinstagram',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 1, 12, 19, 3, 55, 255233, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companytiktok',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 1, 12, 19, 3, 55, 256243, tzinfo=datetime.timezone.utc)),
        ),
    ]
