# Generated by Django 4.2.16 on 2024-11-14 19:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reputation_app', '0038_company_company_storage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companyredditposts',
            old_name='to_posts',
            new_name='nsfw_tag',
        ),
        migrations.RenameField(
            model_name='companyredditposts',
            old_name='to_reels',
            new_name='spoiler_flag',
        ),
        migrations.RemoveField(
            model_name='companyredditposts',
            name='to_stories',
        ),
        migrations.AddField(
            model_name='companyredditposts',
            name='target_subs',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_free_trial_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 19, 19, 6, 12, 171940, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companyfacebook',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 1, 13, 19, 6, 12, 177976, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companyinstagram',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 1, 13, 19, 6, 12, 177976, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companytiktok',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 1, 13, 19, 6, 12, 178973, tzinfo=datetime.timezone.utc)),
        ),
    ]
