# Generated by Django 4.2.16 on 2024-11-16 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reputation_app', '0040_companyposts_is_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyreddit',
            name='subs',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_free_trial_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 21, 9, 41, 38, 498786, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companyfacebook',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 1, 15, 9, 41, 38, 503788, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companyinstagram',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 1, 15, 9, 41, 38, 503788, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companytiktok',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 1, 15, 9, 41, 38, 504808, tzinfo=datetime.timezone.utc)),
        ),
    ]
