# Generated by Django 4.2.16 on 2024-11-16 09:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reputation_app', '0041_companyreddit_subs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_free_trial_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 21, 9, 42, 33, 836536, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companyfacebook',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 1, 15, 9, 42, 33, 841535, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companyinstagram',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 1, 15, 9, 42, 33, 841535, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companyreddit',
            name='subs',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='companytiktok',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 1, 15, 9, 42, 33, 842535, tzinfo=datetime.timezone.utc)),
        ),
    ]
