# Generated by Django 4.2.16 on 2024-11-18 19:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reputation_app', '0047_companyredditposts_brand_flag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_free_trial_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 23, 19, 17, 53, 644750, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companyfacebook',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 1, 17, 19, 17, 53, 649749, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companyinstagram',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 1, 17, 19, 17, 53, 648749, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companytiktok',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 1, 17, 19, 17, 53, 649749, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='uploadedmedia',
            name='media',
            field=models.FileField(upload_to='scheduled_media/'),
        ),
    ]
