# Generated by Django 4.2.16 on 2024-11-21 10:29

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reputation_app', '0050_remove_companyredditposts_agg_comment_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRedditSubs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('subscriber_count', models.TextField(default='')),
                ('user_is_banned', models.BooleanField(default=False)),
                ('sub_rules', models.JSONField(default=dict)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='company',
            name='company_free_trial_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 26, 10, 29, 2, 473132, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companyfacebook',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 1, 20, 10, 29, 2, 478130, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companyinstagram',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 1, 20, 10, 29, 2, 478130, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companytiktok',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 1, 20, 10, 29, 2, 479236, tzinfo=datetime.timezone.utc)),
        ),
    ]
