# Generated by Django 4.2.16 on 2024-11-21 10:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reputation_app', '0051_companyredditsubs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyredditsubs',
            name='sub_rules',
        ),
        migrations.AlterField(
            model_name='company',
            name='company_free_trial_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 26, 10, 34, 34, 888074, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companyfacebook',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 1, 20, 10, 34, 34, 894074, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companyinstagram',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 1, 20, 10, 34, 34, 893074, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companytiktok',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 1, 20, 10, 34, 34, 894074, tzinfo=datetime.timezone.utc)),
        ),
    ]
