# Generated by Django 4.2.16 on 2024-11-21 10:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reputation_app', '0052_remove_companyredditsubs_sub_rules_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyredditsubs',
            name='sub_rules',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_free_trial_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 26, 10, 35, 16, 695710, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companyfacebook',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 1, 20, 10, 35, 16, 701470, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companyinstagram',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 1, 20, 10, 35, 16, 700677, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companytiktok',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 1, 20, 10, 35, 16, 701678, tzinfo=datetime.timezone.utc)),
        ),
    ]
