# Generated by Django 4.2.16 on 2024-11-21 11:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reputation_app', '0053_companyredditsubs_sub_rules_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_free_trial_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 26, 11, 43, 49, 899768, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companyfacebook',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 1, 20, 11, 43, 49, 907805, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companyinstagram',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 1, 20, 11, 43, 49, 906768, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companyredditsubs',
            name='user_is_banned',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='companytiktok',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 1, 20, 11, 43, 49, 908767, tzinfo=datetime.timezone.utc)),
        ),
    ]
