# Generated by Django 4.2.16 on 2024-11-23 09:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reputation_app', '0055_companyreddit_last_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companytiktokposts',
            name='location_tags',
        ),
        migrations.RemoveField(
            model_name='companytiktokposts',
            name='product_tags',
        ),
        migrations.RemoveField(
            model_name='companytiktokposts',
            name='to_posts',
        ),
        migrations.RemoveField(
            model_name='companytiktokposts',
            name='to_reels',
        ),
        migrations.RemoveField(
            model_name='companytiktokposts',
            name='to_stories',
        ),
        migrations.AddField(
            model_name='companytiktokposts',
            name='average_watch_time',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='companytiktokposts',
            name='click_through_rate',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='companytiktokposts',
            name='completion_rate',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='companytiktokposts',
            name='cover_image_url',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='companytiktokposts',
            name='duet_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='companytiktokposts',
            name='mentions',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='companytiktokposts',
            name='profile_visits',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='companytiktokposts',
            name='reach',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='companytiktokposts',
            name='reasons',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='companytiktokposts',
            name='share_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='companytiktokposts',
            name='stitch_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='companytiktokposts',
            name='video_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companytiktokposts',
            name='views_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_free_trial_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 28, 9, 10, 2, 93469, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companyfacebook',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 1, 22, 9, 10, 2, 105489, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companyinstagram',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 1, 22, 9, 10, 2, 104471, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companytiktok',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 1, 22, 9, 10, 2, 107126, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companytiktokposts',
            name='comment_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='companytiktokposts',
            name='engagement_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='companytiktokposts',
            name='has_copyright',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='companytiktokposts',
            name='is_published',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='companytiktokposts',
            name='post_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companytiktokposts',
            name='post_link',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='companytiktokposts',
            name='run_copyright',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
