# Generated by Django 4.2.16 on 2024-11-23 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reputation_app', '0056_remove_companytiktokposts_location_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyfacebook',
            name='page_access_token',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='companyfacebook',
            name='pages',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_free_trial_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 28, 19, 24, 44, 676964, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companyfacebook',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 1, 22, 19, 24, 44, 681964, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companyinstagram',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 1, 22, 19, 24, 44, 681964, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companytiktok',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 1, 22, 19, 24, 44, 682965, tzinfo=datetime.timezone.utc)),
        ),
    ]
