# Generated by Django 4.2.16 on 2024-11-25 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reputation_app', '0057_companyfacebook_page_access_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyfacebookposts',
            name='content_id',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_free_trial_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 30, 15, 3, 50, 541335, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companyfacebook',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 1, 24, 15, 3, 50, 546333, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companyinstagram',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 1, 24, 15, 3, 50, 546333, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companytiktok',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 1, 24, 15, 3, 50, 547334, tzinfo=datetime.timezone.utc)),
        ),
    ]
