# Generated by Django 4.2.16 on 2024-11-26 18:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reputation_app', '0058_companyfacebookposts_content_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyfacebook',
            name='page_engaged_users',
        ),
        migrations.RemoveField(
            model_name='companyfacebook',
            name='page_negative_feedback',
        ),
        migrations.AlterField(
            model_name='company',
            name='company_free_trial_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 1, 18, 42, 18, 110128, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companyfacebook',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 1, 25, 18, 42, 18, 115126, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companyinstagram',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 1, 25, 18, 42, 18, 115126, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companytiktok',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 1, 25, 18, 42, 18, 116127, tzinfo=datetime.timezone.utc)),
        ),
    ]
