# Generated by Django 4.2.16 on 2024-12-01 08:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reputation_app', '0060_companypostscomments_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companypostscomments',
            name='author_profile',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_free_trial_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 6, 8, 30, 36, 609436, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companyfacebook',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 1, 30, 8, 30, 36, 615453, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companyinstagram',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 1, 30, 8, 30, 36, 614450, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companytiktok',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 1, 30, 8, 30, 36, 615453, tzinfo=datetime.timezone.utc)),
        ),
    ]
