# Generated by Django 4.2.16 on 2024-12-02 02:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reputation_app', '0062_alter_company_company_free_trial_expiry_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companypostscommentsreplies',
            name='post',
        ),
        migrations.AlterField(
            model_name='company',
            name='company_free_trial_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 7, 2, 4, 58, 256405, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companyfacebook',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 1, 31, 2, 4, 58, 261405, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companyinstagram',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 1, 31, 2, 4, 58, 261405, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companytiktok',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 1, 31, 2, 4, 58, 262433, tzinfo=datetime.timezone.utc)),
        ),
    ]
