# Generated by Django 4.2.16 on 2024-12-02 02:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reputation_app', '0063_remove_companypostscommentsreplies_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companypostscommentsreplies',
            name='parent_comment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_free_trial_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 7, 2, 12, 45, 902168, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companyfacebook',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 1, 31, 2, 12, 45, 907167, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companyinstagram',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 1, 31, 2, 12, 45, 906168, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companytiktok',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 1, 31, 2, 12, 45, 907167, tzinfo=datetime.timezone.utc)),
        ),
    ]
