# Generated by Django 4.2.16 on 2024-12-02 02:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reputation_app', '0064_companypostscommentsreplies_parent_comment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companypostscomments',
            name='is_op',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='companypostscommentsreplies',
            name='is_op',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_free_trial_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 7, 2, 26, 55, 478708, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companyfacebook',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 1, 31, 2, 26, 55, 483707, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companyinstagram',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 1, 31, 2, 26, 55, 483707, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companytiktok',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 1, 31, 2, 26, 55, 484708, tzinfo=datetime.timezone.utc)),
        ),
    ]
