# Generated by Django 4.2.16 on 2024-12-06 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reputation_app', '0069_companyposts_partial_publish_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyposts',
            name='is_video',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_free_trial_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 11, 14, 25, 30, 373902, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companyfacebook',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 2, 4, 14, 25, 30, 378943, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companyinstagram',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 2, 4, 14, 25, 30, 378943, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companytiktok',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 2, 4, 14, 25, 30, 379920, tzinfo=datetime.timezone.utc)),
        ),
    ]
