# Generated by Django 4.2.16 on 2024-12-06 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reputation_app', '0070_companyposts_is_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyfacebookposts',
            name='post_clicks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='companyfacebookposts',
            name='post_impression_type',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_free_trial_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 11, 16, 30, 32, 853292, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companyfacebook',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 2, 4, 16, 30, 32, 859291, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companyinstagram',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 2, 4, 16, 30, 32, 858292, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companytiktok',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 2, 4, 16, 30, 32, 859291, tzinfo=datetime.timezone.utc)),
        ),
    ]
