# Generated by Django 4.2.16 on 2024-12-06 20:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reputation_app', '0071_companyfacebookposts_post_clicks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyposts',
            name='media_thumbnail',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_free_trial_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 11, 20, 17, 48, 960076, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companyfacebook',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 2, 4, 20, 17, 48, 965209, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companyinstagram',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 2, 4, 20, 17, 48, 965209, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companytiktok',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 2, 4, 20, 17, 48, 966210, tzinfo=datetime.timezone.utc)),
        ),
    ]
