# Generated by Django 4.2.16 on 2024-12-20 08:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reputation_app', '0078_companyprivateconversation_sender_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyreviews',
            name='commentor_profile',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_free_trial_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 25, 8, 5, 51, 218190, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companyfacebook',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 2, 18, 8, 5, 51, 224203, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companyinstagram',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 2, 18, 8, 5, 51, 223203, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companytiktok',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 2, 18, 8, 5, 51, 225212, tzinfo=datetime.timezone.utc)),
        ),
    ]
