# Generated by Django 4.2.16 on 2024-12-25 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reputation_app', '0082_alter_company_company_free_trial_expiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyfeaturerequest',
            name='feature_introduced',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='companyfeaturerequest',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_free_trial_expiry',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 30, 15, 32, 21, 744700, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_subscription_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 25, 15, 32, 21, 744700, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companyfacebook',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 2, 23, 15, 32, 21, 751700, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companyinstagram',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 2, 23, 15, 32, 21, 750804, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companytiktok',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 2, 23, 15, 32, 21, 751700, tzinfo=datetime.timezone.utc)),
        ),
    ]
