# Generated by Django 4.2.16 on 2024-12-31 08:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reputation_app', '0091_siteanalytics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteanalytics',
            name='browser',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='siteanalytics',
            name='city',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='siteanalytics',
            name='ip_address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='siteanalytics',
            name='is_mobile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='siteanalytics',
            name='is_pc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='siteanalytics',
            name='is_tablet',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='siteanalytics',
            name='os',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_free_trial_expiry',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 5, 8, 40, 22, 102711, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_subscription_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 31, 8, 40, 22, 103713, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companybotchats',
            name='date_sent',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 31, 8, 40, 22, 103713, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companyfacebook',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 3, 1, 8, 40, 22, 109718, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companyinstagram',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 3, 1, 8, 40, 22, 108713, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companytiktok',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 3, 1, 8, 40, 22, 109718, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='siteanalytics',
            name='date_visited',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 31, 8, 40, 22, 101710, tzinfo=datetime.timezone.utc)),
        ),
    ]
