# Generated by Django 4.2.16 on 2024-12-31 08:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reputation_app', '0092_siteanalytics_browser_siteanalytics_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteanalytics',
            name='error',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='siteanalytics',
            name='is_error',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_free_trial_expiry',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 5, 8, 47, 42, 140140, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='company',
            name='company_subscription_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 31, 8, 47, 42, 140140, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companybotchats',
            name='date_sent',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 31, 8, 47, 42, 141141, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companyfacebook',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 3, 1, 8, 47, 42, 148141, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companyinstagram',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 3, 1, 8, 47, 42, 148141, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='companytiktok',
            name='token_expiry',
            field=models.DateField(default=datetime.datetime(2025, 3, 1, 8, 47, 42, 149140, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='siteanalytics',
            name='date_visited',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 31, 8, 47, 42, 139141, tzinfo=datetime.timezone.utc)),
        ),
    ]
